### PR TITLE
Feat: Move2Kube Cheatsheet

### PR DESCRIPTION
**Pull request by lakshay-nasa**
#108 

image

### CODE REVIEW

**Comment by ashokponkumar** [comment]
This is awesome. Thanks! @HarikrishnanBalagopal please review and merge.

**Comment by HarikrishnanBalagopal** [comment]
@lakshay-nasa Please complete the DCA by signing the PR/commit

**Comment by HarikrishnanBalagopal** [comment]
> @HarikrishnanBalagopal In which directory should I add the source folder? Is ./docs/commands/move2kube_cheatsheet* the correct location? May you please provide guidance on how to complete the DCO for the 'Merge branch 'konveyor:main' into m2k_cheatsheet'? Thank you.

` ./docs/commands/move2kube_cheatsheet/` sure you can add it in that folder if there are multiple files that make the pdf.

You can read this but basically you need to sign the commit using the `-s` flag. You can also add it manually in the commit message.
https://github.com/konveyor/move2kube/blob/main/contributing.md#contributing
https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for
It adds a line, for example:
```
Signed-off-by: seshapad [seshapad@in.ibm.com](mailto:seshapad@in.ibm.com)
```
https://github.com/konveyor/move2kube-website/pull/104

**Comment by lakshay-nasa** [comment]
Closing this pull request due to conflicts. Will submit a new one soon.

**Pull request closed without merging**
